//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLLite_Mongo_Excel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public long Id { get; set; }
        public string ProductName { get; set; }
        public decimal TaxAmount { get; set; }
        public int VendorId { get; set; }
    }
}
